version: "3.8"
services:
  client:
    build: ./client
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - server
  mongodb:
    image: mongo:latest
    ports:
      - "7017:27017"
    volumes:
      - db:/data/db
  server:
    depends_on:
      - mongodb
    build: ./server
    restart: always
    ports:
      - "8877:8877"

volumes:
  db:
